name: dt-infra-pillar-pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch, adjust as needed.
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch, adjust as needed.

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify your Terraform version here.

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Format Check
      run: terraform fmt -check -diff

    - name: Terraform Validate
      run: terraform validate

    - name: Install TFLint (Optional)
      run: |
        curl -LO https://github.com/terraform-linters/tflint/releases/download/v0.35.0/tflint-linux-amd64.zip
        unzip tflint-linux-amd64.zip
        sudo mv tflint /usr/local/bin/

    - name: Terraform Linting (Optional)
      run: tflint

    - name: Install Checkov (Vulnerability Scanning)
      run: |
        curl -sSL https://github.com/bridgecrewio/checkov/releases/download/v2.2.7/checkov_2.2.7-linux-x86_64.tar.gz | tar -xz -C /usr/local/bin

    - name: Checkov Vulnerability Check
      run: checkov -d .  # Scans the entire repository for Terraform vulnerabilities

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Plan Approval (Manual)
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "Manual approval required to proceed."

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Terraform Test (Optional)
      run: terraform output  # Add additional test commands as needed.
