name: dt-infra-pillar-pipeline

on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.5.7" # Specify the Terraform version

jobs:
  terraform:
    name: Terraform Pipeline for AWS
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your region

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init -input=false

      # Validate Terraform
      - name: Terraform Validate
        run: |
          terraform fmt -check
          terraform validate

      # Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Apply Terraform Plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
